### PR TITLE
Add Python 3.* compatibility

### LINKED ISSUE #8: Python 3+ incompatible
BeautifulSoup 3 does not work on Python 3+, recommend moving to BS4
raw_input("…") is now input("…")
print "…" is now print("…")

### PR DESCRIPTION
**Pull request by amalrajan**
I've modified a few lines of code to make the script run on Python >= 3.0. Please do let me know if anything else is to be changed, or if I'm missing out something.

Fixes #8

### CODE REVIEW

**Review by rohithasrk — CHANGES_REQUESTED** [review]
Hi @amalrajan. Thanks for working on this. Can you please fix the travis ci issues too. Some minor styling issues which can be easily solved. :D

**Comment by amalrajan** [comment]
Ping @rohithasrk. Please review this one.

**Review by jayvdb — CHANGES_REQUESTED** [review]
Add Python 3.4 or 3.5 or 3.6 to `.travis.yml`

**Comment by amalrajan** [comment]
@jayvdb Completed. Please review this one.

**Comment by rohithasrk** [comment]
Thanks for working on this! Had to merge another PR because of ease of conflict resolution. Apologies!

**Pull request closed without merging**
