### PR TITLE
Adds proxy support and adds colored output

### PR DESCRIPTION
**Pull request by vinamarora8**
Given that the person has exported $http_proxy and $https_proxy (which they need to if they are using Internet over a proxy server), their proxy settings will be used by requests. The program won't run without this.

Please try this on a non-proxy Internet connection.

### CODE REVIEW

**Comment by rohithasrk** [comment]
This error.

vinerror

**Comment by vinamarora8** [comment]
The following commit should fix it

**Comment by rohithasrk** [comment]
Yeah. Seems fine. Do some PEP-8 checks before the final commit.
You may want to use this https://github.com/PyCQA/pycodestyle

**Comment by vinamarora8** [comment]
Fixed most of the issues caused by me. Leaving the long line issue, which you don't seem to care about

**Comment by rohithasrk** [comment]
Long line is acceptable to an extent. Anyways, merging it now. Thanks :)

**Pull request merged**
